use serde::{de::DeserializeOwned, Deserialize, Serialize};
use std::marker::PhantomData;

/// Default ID type to use if none is specified.
pub type DefaultType = String;

/// Denotes an ID that can be generated by the database.
pub trait GeneratedIdGuard: IdGuard {}

/// Guards the underlying type in an [`Id`].
pub trait IdGuard: ToString + Serialize + DeserializeOwned + Clone + Send + Sync {}
impl<T: ToString + Serialize + DeserializeOwned + Clone + Send + Sync> IdGuard for T {}

/// Wrapper struct for a model ID, which holds the model type.
#[derive(Debug)]
pub struct Id<M, I: IdGuard = DefaultType> {
    /// The inner value of the id type, optional.  If none, serializing will skip this field.  If the type is ObjectId, this will be generated by the MongoDB server.
    pub(crate) inner: Option<I>,
    _marker: PhantomData<M>,
}

impl<M, I: IdGuard> Id<M, I> {
    pub fn is_none(&self) -> bool {
        self.inner.is_none()
    }
}

impl<M, I: IdGuard> Clone for Id<M, I> {
    fn clone(&self) -> Self {
        Self {
            inner: self.inner.clone(),
            _marker: PhantomData,
        }
    }
}

impl<M, I: IdGuard> Default for Id<M, I> {
    fn default() -> Self {
        Self {
            inner: None,
            _marker: PhantomData,
        }
    }
}

impl<M, I: IdGuard> From<I> for Id<M, I> {
    fn from(id: I) -> Self {
        Self {
            inner: Some(id),
            _marker: PhantomData,
        }
    }
}

impl<M, I> Id<M, I>
where
    I: GeneratedIdGuard,
{
    pub fn none() -> Self {
        return Self {
            inner: None,
            _marker: PhantomData,
        };
    }
}

impl<M, I: IdGuard> Serialize for Id<M, I> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.inner.serialize(serializer)
    }
}

impl<'de, M, I: IdGuard> Deserialize<'de> for Id<M, I> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let id = Deserialize::deserialize(deserializer)?;
        Ok(Self {
            inner: id,
            _marker: PhantomData,
        })
    }
}

#[cfg(feature = "bson")]
#[cfg_attr(docsrs, doc(cfg(any(feature = "bson", feature = "mongodb"))))]
mod bson {
    use crate::error::MustyError;

    use super::*;
    use ::bson::{oid::ObjectId, to_bson, Bson};

    impl GeneratedIdGuard for ObjectId {}

    impl<M, I: IdGuard> TryFrom<Id<M, I>> for ObjectId {
        type Error = MustyError;

        fn try_from(id: Id<M, I>) -> Result<Self, Self::Error> {
            match id.inner {
                Some(id) => Ok(ObjectId::parse_str(&id.to_string())?),
                None => Err(crate::error::MustyError::Other(anyhow::anyhow!(
                    "Id is None"
                ))),
            }
        }
    }

    impl<M, I: IdGuard> TryFrom<&Id<M, I>> for ObjectId {
        type Error = MustyError;

        fn try_from(id: &Id<M, I>) -> Result<Self, Self::Error> {
            match &id.inner {
                Some(id) => Ok(ObjectId::parse_str(&id.to_string())?),
                None => Err(crate::error::MustyError::Other(anyhow::anyhow!(
                    "Id is None"
                ))),
            }
        }
    }

    impl<M, I> TryFrom<Id<M, I>> for Bson
    where
        I: IdGuard,
    {
        type Error = MustyError;

        fn try_from(id: Id<M, I>) -> Result<Self, Self::Error> {
            match id.inner {
                Some(id) => bson::to_bson(&id).map_err(|e| MustyError::Other(e.into())),
                None => Ok(Bson::Null),
            }
        }
    }

    impl<M, I> TryFrom<&Id<M, I>> for Bson
    where
        I: IdGuard,
    {
        type Error = MustyError;

        fn try_from(id: &Id<M, I>) -> Result<Self, Self::Error> {
            match &id.inner {
                Some(id) => bson::to_bson(id).map_err(|e| MustyError::Other(e.into())),
                None => Ok(Bson::Null),
            }
        }
    }
}

#[cfg(test)]
mod tests {

    #[test]
    fn serialize() {}

    #[test]
    fn deserialize() {}
}
