[package]
name = "musty-proc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"
darling = "0.14.2"
proc-macro-error = "1"

[features]
default = ["mongodb"]
mongodb = []