name: docs
on:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
jobs:
  cargo:
    name: "docs: build & deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: mdbook
    - run: mdbook build docs 
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/book